### ISSUE TITLE
import

### ISSUE THREAD

**Issue by Jakesh-Bohaju** [zhreshold/mxnet-yolo#25]
Traceback (most recent call last):
  File "E:\python_workspace\mxnet-yolo-master\demo.py", line 7, in <module>
    from detect.detector import Detector
  File "E:\python_workspace\mxnet-yolo-master\detect\detector.py", line 5, in <module>
    from dataset.testdb import TestDB
  File "E:\python_workspace\mxnet-yolo-master\dataset\testdb.py", line 2, in <module>
    from imdb import Imdb
ModuleNotFoundError: No module named 'imdb'

**Comment by zhreshold** [comment]
python 3 compatibility should be fixed now.
