### ISSUE TITLE
method  get_symbol() cannot be invoked correctly

### ISSUE THREAD

**Issue by Alexander-flyer** [zhreshold/mxnet-yolo#38]
## **Environment info**

```
----------Python Info----------
('Version      :', '2.7.12')
('Compiler     :', 'GCC 4.4.7 20120313 (Red Hat 4.4.7-1)')
('Build        :', ('default', 'Jul  2 2016 17:42:40'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '8.1.2')
('Directory    :', '/export/docker/JXQ-23-46-48.h.chinabank.com.cn/saber/mxnet_env/mxnet_2.7/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
('Platform     :', 'Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.3.1611-Core')
('system       :', 'Linux')
('node         :', 'JXQ-240-26-35.h.chinabank.com.cn')
('release      :', '3.10.0-514.el7.x86_64')
('version      :', '#1 SMP Tue Nov 22 16:42:41 UTC 2016')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               2200.000
BogoMIPS:              4400.10
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47
----------Network Test----------
Setting timeout: 10
```

## **maxnet build info**
I have build maxnet as the tutorials as #34 

## **Error Info**

```
Namespace(cpu=True, data_shape=416, deploy_net=False, dir=None, epoch=0, extension=None, force_nms=True, gpu_id=0, images='./data/demo/dog.jpg', mean_b=104, mean_g=117, mean_r=123, network='darknet19', nms_thresh=0.5, prefix='/export/docker/JXQ-23-46-48.h.chinabank.com.cn/saber/mxnet/mxnet-yolo/model/yolo2', show_timer=True, thresh=0.5)
('darknet19', '/export/docker/JXQ-23-46-48.h.chinabank.com.cn/saber/mxnet/mxnet-yolo/model/yolo2', 0, 416, (123, 117, 104), cpu(0))
3
Traceback (most recent call last):
  File "demo.py", line 102, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 42, in get_detector
    net = importlib.import_module('symbol_' + net).get_symbol(len(CLASSES), nms_thresh, force_nms)
TypeError: get_symbol() takes at most 1 argument (3 given)
```

## **Question**
The error occurred when I run `python demo.py --cpu`
What can I do to resolve the problem?
Waiting for your response, thx!

**Comment by lovehuanhuan** [comment]
This project is based on mxnet 0.10.0,so...u have to get older version mxnet

**Comment by zhreshold** [comment]
use darknet19_yolo as network rather than darknet19.
The latter is for image classification base network.
