### ISSUE TITLE
module 'mxnet.symbol' has no attribute 'stack_neighbor'

### ISSUE THREAD

**Issue by Heidisnaps** [zhreshold/mxnet-yolo#5]
Hi.
I have some error.

> module 'mxnet.symbol' has no attribute 'stack_neighbor'

this is my flow:
```
$ git clone https://github.com/zhreshold/mxnet-yolo.git
>> (omit)
$ cd mxnet-yolo
~mxnet-yolo$ git clone --recursive https://github.com/dmlc/mxnet
>> (omit)
~mxnet-yolo$ cd mxnet; 
~mxnet-yolo/mxnet$ make -j4
>> (omit)
~mxnet-yolo/mxnet$ git submodule update --recursive --init
~mxnet-yolo/mxnet$ cd ..
```
after build mxnet, I tried run demo.py
```
~mxnet-yolo$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 100, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 41, in get_detector
    .get_symbol(len(CLASSES), nms_thresh, force_nms)
  File "/home/ubuntu/Notebooks/heidi/test_project/mxdir/mxnet-yolo/symbol/symbol_darknet19_yolo.py", line 25, in get_symbol
    conv5_6 = mx.sym.stack_neighbor(data=conv5_5, kernel=(2, 2), name='stack_downsample')
AttributeError: module 'mxnet.symbol' has no attribute 'stack_neighbor'
```

so I have done your solution(git submodule update --recursive --init) again in the mxnet-yolo directory.

```
~mxnet-yolo$ git submodule update --recursive --init
fatal: reference is not a tree: 37455ca2b2c19ff88b3d1a3075a02a4f49db9dd6
Unable to checkout '37455ca2b2c19ff88b3d1a3075a02a4f49db9dd6' in submodule path 'mxnet'
```

**Comment by CptnKirk** [comment]
I have the same issue.  
`git submodule update --recursive --init`
completes without error.  Just the same error while running demo.py.  I have rebuilt/installed mxnet from source.

**Comment by CptnKirk** [comment]
my mxnet submodule build fails.  Any tips?

```
/usr/local/cuda/bin/nvcc -c -o build/src/operator/rnn_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=[sm_61,compute_61] --fatbin-options -compress-all -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -DNDEBUG=1 -I/home/jim/data/git/mxnet-yolo/mxnet/mshadow/ -I/home/jim/data/git/mxnet-yolo/mxnet/dmlc-core/include -fPIC -I/home/jim/data/git/mxnet-yolo/mxnet/nnvm/include -I/home/jim/data/git/mxnet-yolo/mxnet/dlpack/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMXNET_USE_LAPACK -DMSHADOW_USE_CUDNN=1  -I/home/jim/data/git/mxnet-yolo/mxnet/cub -DMXNET_USE_NVRTC=0" src/operator/rnn.cu
src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNDescriptor_t" is incompatible with parameter of type "cudnnHandle_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "uint32_t" is incompatible with parameter of type "cudnnRNNDescriptor_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDropoutDescriptor_t" is incompatible with parameter of type "int"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNInputMode_t" is incompatible with parameter of type "cudnnDropoutDescriptor_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDirectionMode_t" is incompatible with parameter of type "cudnnRNNInputMode_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnRNNMode_t" is incompatible with parameter of type "cudnnDirectionMode_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: argument of type "cudnnDataType_t" is incompatible with parameter of type "cudnnRNNMode_t"
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

src/operator/./cudnn_rnn-inl.h(435): error: too few arguments in function call
          detected during:
            instantiation of "void mxnet::op::CuDNNRNNOp<DType>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with DType=float]" 
(54): here
            instantiation of "mxnet::op::CuDNNRNNOp<DType>::CuDNNRNNOp(mxnet::op::RNNParam) [with DType=float]" 
src/operator/rnn.cu(20): here

8 errors detected in the compilation of "/tmp/tmpxft_000022b6_00000000-17_rnn.compute_61.cpp1.ii".
Makefile:274: recipe for target 'build/src/operator/rnn_gpu.o' failed
make: *** [build/src/operator/rnn_gpu.o] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by jianglong98** [comment]
I have similar issue like below, pls advise, thanks!
mxnet-yolo$ git fetch --recurse-submodules
Fetching submodule mxnet
Fetching submodule mxnet/cub
Fetching submodule mxnet/dlpack
Fetching submodule mxnet/dmlc-core
Fetching submodule mxnet/mshadow
Fetching submodule mxnet/nnvm
Fetching submodule mxnet/nnvm/dmlc-core
Fetching submodule mxnet/nnvm/plugin/nnvm-fusion
Fetching submodule mxnet/ps-lite

mxnet-yolo$ git submodule update --recursive --init
error: no such remote ref 37455ca2b2c19ff88b3d1a3075a02a4f49db9dd6
Fetched in submodule path 'mxnet', but it did not contain 37455ca2b2c19ff88b3d1a3075a02a4f49db9dd6. Direct fetching of that commit failed.

**Comment by jianglong98** [comment]
mxnet-yolo$ python demo.py --cpu
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import tools.find_mxnet
  File "/Users/jianglong/Project_ODS/mxnet-yolo/tools/find_mxnet.py", line 7, in <module>
    import mxnet as mx
  File "/Users/jianglong/Project_ODS/mxnet-yolo/tools/../mxnet/python/mxnet/__init__.py", line 25, in <module>
    from .base import MXNetError
  File "/Users/jianglong/Project_ODS/mxnet-yolo/tools/../mxnet/python/mxnet/base.py", line 110, in <module>
    _LIB = _load_lib()
  File "/Users/jianglong/Project_ODS/mxnet-yolo/tools/../mxnet/python/mxnet/base.py", line 101, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "/Users/jianglong/Project_ODS/mxnet-yolo/tools/../mxnet/python/mxnet/libinfo.py", line 59, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
/Users/jianglong/Project_ODS/mxnet-yolo/mxnet/python/mxnet/libmxnet.dylib
/Users/jianglong/Project_ODS/mxnet-yolo/mxnet/python/mxnet/../../lib/libmxnet.dylib
/Users/jianglong/Project_ODS/mxnet-yolo/mxnet/python/mxnet/../../build/Release/libmxnet.dylib
/Users/jianglong/Project_ODS/mxnet-yolo/mxnet/python/mxnet/libmxnet.so
/Users/jianglong/Project_ODS/mxnet-yolo/mxnet/python/mxnet/../../lib/libmxnet.so
/Users/jianglong/Project_ODS/mxnet-yolo/mxnet/python/mxnet/../../build/Release/libmxnet.so

**Comment by zhreshold** [comment]
use
```
git clone --recursive https://github.com/zhreshold/mxnet-yolo
cd mxnet-yolo/mxnet
# try to build it using the official installation tutorial
```
don't trick submodule from offical repo

**Comment by jianglong98** [comment]
Thanks, Zhreshold!
How to build mxnet using official installation tutorial? Actually I want to know which mode need to follow: Pip, Docker or virtualenv?  I have installed mxnet before this project.

**Comment by jianglong98** [comment]
mxnet$ pwd
/Users/jianglong/Project_ODS/mxnet-yolo/mxnet
mxnet$ pip install mxnet
Requirement already satisfied: mxnet in /Users/jianglong/anaconda/lib/python2.7/site-packages
Requirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from mxnet)

**Comment by zhreshold** [comment]
@jianglong98  You have to build from source, as I have mentioned the official repo is lacking some operators, pip, docker won't work at all.

**Comment by jianglong98** [comment]
I build up mxnet from source, but still have issue below when:
1: the **import tools.find_mxnet** is in the demo.py, the demo.py was executed and result is the same as before.

2: the **import tools.find_mxnet** was commented out, then execute result is below:
/Users/jianglong/anaconda/bin/python /Users/jianglong/Project_ODS/mxnet-yolo/demo.py
Traceback (most recent call last):
  File "/Users/jianglong/Project_ODS/mxnet-yolo/demo.py", line 100, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "/Users/jianglong/Project_ODS/mxnet-yolo/demo.py", line 41, in get_detector
    .get_symbol(len(CLASSES), nms_thresh, force_nms)
  File "/Users/jianglong/Project_ODS/mxnet-yolo/symbol/symbol_darknet19_yolo.py", line 30, in get_symbol
    conv5_6 = mx.sym.stack_neighbor(data=conv5_5, kernel=(2, 2), name='stack_downsample')
AttributeError: 'module' object has no attribute 'stack_neighbor'

**Comment by jianglong98** [comment]
After review find_mxnet.py, I changed the mxnet0 into mxnet in 2nd line, is that useful?
import mxnet**0** as mx

**Comment by tlc** [comment]
> git clone --recursive https://github.com/zhreshold/mxnet-yolo
> cd mxnet-yolo/mxnet
> \# try to build it using the official installation tutorial
> 

You might want to put this on the front page README before the spot where people are sent to the "Instructions" link which tells them to download the official mxnet.

**Comment by blakeliu** [comment]
I flowed http://mxnet.incubator.apache.org/get_started/windows_setup.html, build x64 gpu version, and python interface. Last run demo.py,and it was still failed !!!
 **conv5_6 = mx.sym.stack_neighbor(data=conv5_5, kernel=(2, 2), name='stack_downsample')
AttributeError: module 'mxnet.symbol' has no attribute 'stack_neighbor'**



(C:\Anaconda3) E:\dl\lib\mxnet\incubator-mxnet\python>conda info
Current conda install:
               platform : win-64
          conda version : 4.3.27
         python version : 3.5.2.final.0

(C:\Anaconda3) E:\dl\lib\mxnet\incubator-mxnet\python>conda list mxnet
packages in environment at C:\Anaconda3:
mxnet                     0.12.0                    <pip>

**Comment by CptnKirk** [comment]
You need to uninstall mxnet. Then build and install the mxnet from the mxnet dir of this project. Not the main project.

**Comment by blakeliu** [comment]
win10 vs2015  build x64 gpu version ,error:
e:\cv\object_detection\yolo\mxnet-yolo\mxnet\src\operator\contrib\./yolo_output-inl.h(61): error C2398: 元素“1”: 从“double”转换到“float”需要收缩转换
3>
3>e:\cv\object_detection\yolo\mxnet-yolo\mxnet\src\operator\contrib\./yolo_output-inl.h(61): error C2398: 元素“2”: 从“double”转换到“float”需要收缩转换

**Comment by euraka71** [comment]
I uninstall official mxnet.And install this by
```
cd mxnet-yolo/mxnet/python
python setup.py install
```
on win10.Then run demo.py,it still shows that

> module 'mxnet.symbol' has no attribute 'stack_neighbor'

Anyone can tell me what's wrong?
And I open symbol.py.It doesn't contain something like 'def  stack_neighbor(...,...,...):...'
I just find ' stack_neighbor' in 'mxnet-yolo\mxnet\src\operator\tensor\matrix_op.cc'.
